//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logisto.Novelco {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/novelco", ConfigurationName="Novelco.ExchangeNovelcoPortType")]
    public interface ExchangeNovelcoPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/novelco#ExchangeNovelco:SetDeliverValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Logisto.Novelco.ConsignmentNoteResponseStructure SetDeliverValue(Logisto.Novelco.ConsignmentNote ConsignmentNote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/novelco#ExchangeNovelco:SetDeliverValue", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Logisto.Novelco.ConsignmentNoteResponseStructure> SetDeliverValueAsync(Logisto.Novelco.ConsignmentNote ConsignmentNote);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/novelco#ExchangeNovelco:GetPaymentDocumentsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Logisto.Novelco.GetPaymentDocumentsListResponse GetPaymentDocumentsList(Logisto.Novelco.GetPaymentDocumentsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/novelco#ExchangeNovelco:GetPaymentDocumentsList", ReplyAction="*")]
        System.Threading.Tasks.Task<Logisto.Novelco.GetPaymentDocumentsListResponse> GetPaymentDocumentsListAsync(Logisto.Novelco.GetPaymentDocumentsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/novelco#ExchangeNovelco:UnregisterChanges", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool UnregisterChanges();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/novelco#ExchangeNovelco:UnregisterChanges", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> UnregisterChangesAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="NOVELCO")]
    public partial class ConsignmentNote : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deliverValueNumberField;
        
        private System.DateTime deliverValueDateField;
        
        private string bankAccountField;
        
        private string bIKField;
        
        private string swiftField;
        
        private string currensyField;
        
        private string tINField;
        
        private string rGCField;
        
        private string partnerNameField;
        
        private bool createInvoiceField;
        
        private ServicesList[] servicesListField;
        
        private string contractNumberField;
        
        private System.Nullable<System.DateTime> contractDateField;
        
        private bool thisSellingField;
        
        private string incomingDocumentNumberField;
        
        private string invoiceNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DeliverValueNumber {
            get {
                return this.deliverValueNumberField;
            }
            set {
                this.deliverValueNumberField = value;
                this.RaisePropertyChanged("DeliverValueNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DeliverValueDate {
            get {
                return this.deliverValueDateField;
            }
            set {
                this.deliverValueDateField = value;
                this.RaisePropertyChanged("DeliverValueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BankAccount {
            get {
                return this.bankAccountField;
            }
            set {
                this.bankAccountField = value;
                this.RaisePropertyChanged("BankAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string BIK {
            get {
                return this.bIKField;
            }
            set {
                this.bIKField = value;
                this.RaisePropertyChanged("BIK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Swift {
            get {
                return this.swiftField;
            }
            set {
                this.swiftField = value;
                this.RaisePropertyChanged("Swift");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Currensy {
            get {
                return this.currensyField;
            }
            set {
                this.currensyField = value;
                this.RaisePropertyChanged("Currensy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string TIN {
            get {
                return this.tINField;
            }
            set {
                this.tINField = value;
                this.RaisePropertyChanged("TIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string RGC {
            get {
                return this.rGCField;
            }
            set {
                this.rGCField = value;
                this.RaisePropertyChanged("RGC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PartnerName {
            get {
                return this.partnerNameField;
            }
            set {
                this.partnerNameField = value;
                this.RaisePropertyChanged("PartnerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool CreateInvoice {
            get {
                return this.createInvoiceField;
            }
            set {
                this.createInvoiceField = value;
                this.RaisePropertyChanged("CreateInvoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ServicesList", IsNullable=true, Order=10)]
        public ServicesList[] ServicesList {
            get {
                return this.servicesListField;
            }
            set {
                this.servicesListField = value;
                this.RaisePropertyChanged("ServicesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string ContractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
                this.RaisePropertyChanged("ContractNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> ContractDate {
            get {
                return this.contractDateField;
            }
            set {
                this.contractDateField = value;
                this.RaisePropertyChanged("ContractDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool ThisSelling {
            get {
                return this.thisSellingField;
            }
            set {
                this.thisSellingField = value;
                this.RaisePropertyChanged("ThisSelling");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string IncomingDocumentNumber {
            get {
                return this.incomingDocumentNumberField;
            }
            set {
                this.incomingDocumentNumberField = value;
                this.RaisePropertyChanged("IncomingDocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("InvoiceNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="NOVELCO")]
    public partial class ServicesList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceNameField;
        
        private float priceField;
        
        private string vATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string VAT {
            get {
                return this.vATField;
            }
            set {
                this.vATField = value;
                this.RaisePropertyChanged("VAT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="NOVELCO")]
    public partial class PaymentDocument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentIDField;
        
        private string documentTypeField;
        
        private string baseDocumentNumberField;
        
        private string bankAccountField;
        
        private string bIK_SwiftField;
        
        private string descriptionField;
        
        private string currencyField;
        
        private string tINField;
        
        private string rGCField;
        
        private string amountField;
        
        private bool markingRemovalField;
        
        private System.DateTime paymentDateField;
        
        private string incomingDocumentNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
                this.RaisePropertyChanged("DocumentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("DocumentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BaseDocumentNumber {
            get {
                return this.baseDocumentNumberField;
            }
            set {
                this.baseDocumentNumberField = value;
                this.RaisePropertyChanged("BaseDocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BankAccount {
            get {
                return this.bankAccountField;
            }
            set {
                this.bankAccountField = value;
                this.RaisePropertyChanged("BankAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BIK_Swift {
            get {
                return this.bIK_SwiftField;
            }
            set {
                this.bIK_SwiftField = value;
                this.RaisePropertyChanged("BIK_Swift");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TIN {
            get {
                return this.tINField;
            }
            set {
                this.tINField = value;
                this.RaisePropertyChanged("TIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RGC {
            get {
                return this.rGCField;
            }
            set {
                this.rGCField = value;
                this.RaisePropertyChanged("RGC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9 )]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool MarkingRemoval {
            get {
                return this.markingRemovalField;
            }
            set {
                this.markingRemovalField = value;
                this.RaisePropertyChanged("MarkingRemoval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=11)]
        public System.DateTime PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
                this.RaisePropertyChanged("PaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string IncomingDocumentNumber {
            get {
                return this.incomingDocumentNumberField;
            }
            set {
                this.incomingDocumentNumberField = value;
                this.RaisePropertyChanged("IncomingDocumentNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="NOVELCO")]
    public partial class ConsignmentNoteResponseStructure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultStringField;
        
        private bool succesfullyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ResultString {
            get {
                return this.resultStringField;
            }
            set {
                this.resultStringField = value;
                this.RaisePropertyChanged("ResultString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Succesfully {
            get {
                return this.succesfullyField;
            }
            set {
                this.succesfullyField = value;
                this.RaisePropertyChanged("Succesfully");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentDocumentsList", WrapperNamespace="http://localhost/novelco", IsWrapped=true)]
    public partial class GetPaymentDocumentsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/novelco", Order=0)]
        public System.DateTime Date;
        
        public GetPaymentDocumentsListRequest() {
        }
        
        public GetPaymentDocumentsListRequest(System.DateTime Date) {
            this.Date = Date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaymentDocumentsListResponse", WrapperNamespace="http://localhost/novelco", IsWrapped=true)]
    public partial class GetPaymentDocumentsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/novelco", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="NOVELCO")]
        public Logisto.Novelco.PaymentDocument[] @return;
        
        public GetPaymentDocumentsListResponse() {
        }
        
        public GetPaymentDocumentsListResponse(Logisto.Novelco.PaymentDocument[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExchangeNovelcoPortTypeChannel : Logisto.Novelco.ExchangeNovelcoPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExchangeNovelcoPortTypeClient : System.ServiceModel.ClientBase<Logisto.Novelco.ExchangeNovelcoPortType>, Logisto.Novelco.ExchangeNovelcoPortType {
        
        public ExchangeNovelcoPortTypeClient() {
        }
        
        public ExchangeNovelcoPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExchangeNovelcoPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeNovelcoPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeNovelcoPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Logisto.Novelco.ConsignmentNoteResponseStructure SetDeliverValue(Logisto.Novelco.ConsignmentNote ConsignmentNote) {
            return base.Channel.SetDeliverValue(ConsignmentNote);
        }
        
        public System.Threading.Tasks.Task<Logisto.Novelco.ConsignmentNoteResponseStructure> SetDeliverValueAsync(Logisto.Novelco.ConsignmentNote ConsignmentNote) {
            return base.Channel.SetDeliverValueAsync(ConsignmentNote);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Logisto.Novelco.GetPaymentDocumentsListResponse Logisto.Novelco.ExchangeNovelcoPortType.GetPaymentDocumentsList(Logisto.Novelco.GetPaymentDocumentsListRequest request) {
            return base.Channel.GetPaymentDocumentsList(request);
        }
        
        public Logisto.Novelco.PaymentDocument[] GetPaymentDocumentsList(System.DateTime Date) {
            Logisto.Novelco.GetPaymentDocumentsListRequest inValue = new Logisto.Novelco.GetPaymentDocumentsListRequest();
            inValue.Date = Date;
            Logisto.Novelco.GetPaymentDocumentsListResponse retVal = ((Logisto.Novelco.ExchangeNovelcoPortType)(this)).GetPaymentDocumentsList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Logisto.Novelco.GetPaymentDocumentsListResponse> Logisto.Novelco.ExchangeNovelcoPortType.GetPaymentDocumentsListAsync(Logisto.Novelco.GetPaymentDocumentsListRequest request) {
            return base.Channel.GetPaymentDocumentsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Logisto.Novelco.GetPaymentDocumentsListResponse> GetPaymentDocumentsListAsync(System.DateTime Date) {
            Logisto.Novelco.GetPaymentDocumentsListRequest inValue = new Logisto.Novelco.GetPaymentDocumentsListRequest();
            inValue.Date = Date;
            return ((Logisto.Novelco.ExchangeNovelcoPortType)(this)).GetPaymentDocumentsListAsync(inValue);
        }
        
        public bool UnregisterChanges() {
            return base.Channel.UnregisterChanges();
        }
        
        public System.Threading.Tasks.Task<bool> UnregisterChangesAsync() {
            return base.Channel.UnregisterChangesAsync();
        }
    }
}
